version: '3'
services:
  postgres:
    restart: unless-stopped
    container_name: geo
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      DEBUG: "false"
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB:  geo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-p 5432"
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8384:8080
    environment:
      - 'TZ=Europe/Moscow'