import type { EntityManager } from '@mikro-orm/core';
import { Seeder } from '@mikro-orm/seeder';
import { Project } from '../src/project/project.entity';
import { Species } from '../src/species/species.entity';
import { Address } from '../src/address/address.entity';
import { Sample } from '../src/sample/sample.entity';
import { User } from '../src/user/user.entity';

export class InitSeeder extends Seeder {
    async run(em: EntityManager): Promise<void> {
        em.create(User, {
            name: 'Admin',
            isAdmin: true,
            email: 'kraash@bk.ru',
            password:
                '$2b$10$FwrRwZK3lT9Lmw4ubLB4weT2Td9BVjBmlQX4JI1FuM0XGnh8Ubax2',
        });

        em.create(Project, {
            name: 'Первый',
            userId: 1,
        });

        em.create(Project, {
            name: 'Новый 2023',
            userId: 1,
        });

        for (let i = 1; i < 16; i++) {
            em.create(Sample, {
                name: `Образец ${i}`,
                serial: i,
                projectId: 1,
            });
        }
        const names = [
            'Abiskomyia',
            'Ablabesmyia',
            'Acalcarella',
            'Acamptocladius',
            'Acricotopus',
            'Allopsectrocladius',
            'Brillia',
            'Chaetocladius',
            'Chaetocladius dentiforceps-type',
            'Chaetocladius piger-type',
            'Chaetocladius type B',
            'Chironomus anthracinus-type',
            'Chironomus plumosus-type',
            'Chironomini larvula',
            'Cladopelma lateralis',
            'Cladopelma laccophila',
            'Cladotanytarsus mancus-type',
            `Cladotanytarsus mancus 'with spur'`,
            'Constempellina - Thienemanniola',
            'Corynocera ambigua',
            'Corynocera oliveri-type',
            'Corynoneura arctica-type',
            'Corynoneura carriana-type',
            'Corynoneura coronata-type',
            'Corynoneura edwardsi-type',
            'Corynoneura lobata',
            'Cricotopus bicinctus-type',
            'Cricotopus type C',
            'Cricotopus cylindraceus-type',
            'Cricotopus intersectus-type',
            'Cricotopus laricomalis-type',
            'Cricotopus obnixus-type',
            'Cricotopus sylvestris-type',
            'Cricotopus trifascia-type',
            'Cricotopus trifasciatus-type',
            'Cricotopus type P',
            'Cryptochironomus',
            'Demicryptochironomus',
            'Derotanypus',
            'Diamesa species unknown',
            'Diamesa zernyi/cinerella-type',
            'Dicrotendipes nervosus-type',
            'Dicrotendipes notatus-type',
            'Diplocladius',
            'Doncricotopus',
            'Einfeldia  natchitocheae-type',
            'Einfeldia pagana-type',
            'Endochironomus albipennis-type',
            'Endochironomus impar-type',
            'Endochironomus tendens-type',
            'Eukiefferiella devonica-type',
            'Eukiefferiella fittkaui-type',
            'Eukiefferiella claripennis-type',
            'Eurycnemus',
            'Georthocladius',
            'Glyptotendipes barbipes-type',
            'Glyptotendipes pallens-type',
            'Glyptotendipes severini-type',
            'Harnischia',
            'Heterotanytarsus',
            'Heterotrissocladius grimshawi-type',
            'Heterotrissocladius maeaeri-type 1',
            'Heterotrissocladius maeaeri-type 2',
            'Heterotrissocladius marcidus-type',
            'Heterotrissocladius subpilosus-type',
            'Hydrobaenus conformis-type',
            'Hydrobaenus johannseni-type',
            'Hydrobaenus lugubris-type',
            'Labrundinia',
            'Lasiodiamesa',
            'Lauterborniella',
            'Limnophyes - Paralimnophyes',
            'Lipiniella',
            'Macropelopia',
            'Mesocricotopus',
            'Metriocnemus eurynotus-type',
            'Metriocnemus fuscipes-type',
            'Metriocnemus',
            'Micropsectra contracta-type',
            'Micropsectra insignilobus-type',
            'Micropsectra palidula-type',
            'Micropsectra radialis-type',
            'Microchironomus',
            'Microtendipes pedellus-type',
            'Microtendipes rydalensis-type',
            'Monopelopia',
            'Monodiamesa',
            'Nanocladius branchicolus-type',
            'Nanocladius balticus-type',
            'Nanocladius rectinervis-type',
            'Nilothauma',
            'Oliveridia',
            'Omisus',
            'Orthoclasius/Cricotopus',
            'Orthocladius consobrinus-type',
            'Orthocladius oliveri-type',
            'Orthocladius trigonolabris-type',
            'Orthocladius type I',
            'Orthocladius type S',
            'Pagastiella',
            'Parachaetocladius',
            'Parachironomus varus-type',
            'Parachironomus vitosus-type',
            'Paracladius',
            'Paracladopelma',
            'Paracricotopus',
            'Parakiefferiella type A',
            'Parakiefferiella bathophila-type',
            'Parakiefferiella nigra-type',
            'Parakiefferiella nigra type 2',
            'Parakiefferiella triquetra-type',
            'Paralauterborniella',
            'Paraphaenocladius - Parametriocnemus',
            'Paratanytarsus austriacus-type',
            'Paratanytarsus penicillatus-type',
            'Paratanytarsus',
            'Paratendipes',
            'Paratendipes albimanus',
            'Phaenopsectra',
            'Phaenopsectra type A',
            'Phaenopsectra flavipes-type',
            'Polypedilum nubeculosum-type',
            'Polypedilum nubifer-type',
            'Polypedilum sordens-type',
            'Potthastia type 2',
            'Procladius',
            'Prodiamesa',
            'Propsilicerus jacuticus-type',
            'Propsilocerus lacustris-type',
            'Propsilocerus type N',
            'Protanypus',
            'Psectrocladius (Mesopsectrocladius) barbatipes-type',
            'Psectrocladius barbimanus-type',
            'Psectrocladius calcaratus type 2',
            'Psectrocladius flavus-type',
            'Psectrocladius psilopterus-type',
            'Psectrocladius septentrionalis-type',
            'Psectrocladius sordidellus-type',
            'Psectrocladius broad',
            'Psectrocladius narrow',
            'Pseudochironomus',
            'Pseudodiamesa',
            'Pseudorthocladius',
            'Pseudosmittia',
            'Rheocricotopus chalybeatus-type',
            'Rheocricotopus effusus-type',
            'Rheocricotopus fuscipes-type',
            'Rheocricotopus',
            'Rheotanytarsus',
            'Sergentia coracina-type',
            'Smittia - Parasmittia',
            'Stempellina',
            'Stempellina type K',
            'Stempellinella - Zavrelia',
            'Stenochironomus',
            'Stilocladius',
            'Stictochironomus',
            'Stictochironomus type B',
            'Symposiocladius',
            'Synorthocladius',
            'Tanypus',
            'Tanytarsus chinyensis-type',
            'Tanytarsus glabrescens-type',
            'Tanytarsus gracilentus-type',
            'Tanytarsus lactescens-type',
            'Tanytarsus lugens-type',
            'Tanytarsus no spur',
            'Tanytarsus mendax-type',
            'Tanytarsus nemorosus-type',
            'Tanytarsus pallidicornis-type',
            'Tanytarsus pallidicornis-type 2',
            'Thienemanniella clavicornis-type',
            'Thienemanniella type E',
            'Thienemannimyia-group',
            'Tribelos',
            'Trissocladius',
            'Tvetenia bavarica-type',
            'Tvetenia sp',
            'Xenochironomus',
            'Zalutschia type A',
            'Zalutschia type B',
            'Zalutschia mucronata-type',
            'Zalutschia zalutschicola-type',
            'Zavreliella',
            'Chironomini undiff.',
            'Tanytarsini undiff.',
            'Orthocladiinae undiff.',
            'Pentaneurini undiff.',
            'Corynoneura Undiff',
            'Diamesinae  Undiff',
        ];
        const nameSpecies = names.map((n) => ({
            name: n,
        }));
        const species = [];
        nameSpecies.forEach((n) =>
            species.push(
                em.create(Species, {
                    name: n.name,
                })
            )
        );

        for (let i = 1; i < 16; i++) {
            em.create(Address, {
                speciesId: i,
                sampleId: i,
                projectId: 1,
                glass: 1,
                slide: 1,
            });
        }
    }
}
